language: csharp
solution: SuperEngine.sln
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo apt-get install mono-devel
script:
  - xbuild /p:Configuration=Release SuperEngine.sln
  - mono ./packages/xunit.runners.2.0.0-rc1-build2826/tools/xunit.console.exe ./SuperEngine.Tests/bin/Release/SuperEngine.Tests.dll
