language: csharp
solution: SuperEngine-Travis.sln
script:
  - xbuild /p:NoWarn=0612,1591 /p:Configuration=Release SuperEngine-Travis-Dependencies.sln
  - xbuild /p:Configuration=Release SuperEngine-Travis.sln
